language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "ieqG363XI95aYM6fQMD/u6Zb7aRrYx5fGlAKjVPvc2B1fNpGyVOk3ffoGgH7Fy62rJ9q93c7E/dvf9+NJ4SdrSrSQwa7uBesutZXPGPZ4/il/nOK9YX1w8tyMF9Fvgd0vnbfdUqA8/JbV19bz1xu5TuGaAclMPMGPs4W/NJWv6l4g8tIxG/Vz5TOCHOQktQ1+iu5h5OtdJBomUQ1bU9uK6q0jqunfiXa5YuJ7tp0nNKKXGxtuBkfmOcbv+yG/I4f38fM6804quyPBqWqRhAzqSspneq9oRhUMfjHEW9yHoaEQQE+I0mLH4Unc7M4cDzVnE+0wrx6FAv6mvmuZue7Ydgu/hKAsi0s4C11fjUymAvXwYgaPUwbrQ6e9VvgKW/Hu+77TupOWLeChB5AGFud+81GRrfkRzGsBr4WN2+DwDy1VTExB3zkCqKist26tUAmW8tMU8ZIO1yKu0b7qUCh6Fm8SGJjxw3LwNxM5LCc9FrKfQVDj6u77duvcrjUFQp1tkm4BF4Ez0P3NB/tzHsaQjZtF+i1hREgxqOheE/m5SVHmCy2al2HLpf3P9MPV8vb2NRVICO99GZjnqdceDQPTHTdebmCDFmOXNaWq9GjpzELZ2tnMXCaovXs/+fWUDjKEKruGIIU6LGxHGd7imy82qp2f9jMiFUwH5QaHWbnWK0="
  app:
    master: webmathcalculator