language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app:
    master: webmathcalculator
env:
  global:
    secure: YXbb7is7S2Vq6YKlbORi0lpXYVF9Isye0WUSk/ZHOd3KmwkfapioOyTyy9vpN5PslvHSGziEb3mk0++YbRUyLG2Z0IodFOoFP9WmkwnZKqM3gJCiNeYHJofmr1fEevBiY6D9e6No2aeqtm5O7gh48JMPb37RZt1Wx6ibESmdLWtyc/fQ28Ck42rbKWLVZUWeNxN6+/CLwvsSyzwxlEUj7m5WBe/CtQ7aCpWMG5tslAkLFPfquP0lDWN37VsL6T9GOPEJWwT84EWosG6hKT8ajsUSnfnAYFTFtJp1e3knNBmkiUQkAMdU6IjPx3Gt9LpjQOD57BB8PU0HSvLfXIo/DchVnu3/L0UALpmsO4Y2fCNWy71VvABdhtZaRik52LwXCEgu3DZihB1L5x8cFwbbOLuUZq8Dvnm1UnF/0OrA0liFlYyUD0QlGYJ3KvbCiP+SBg3aJX3JGwMcElSDfsmM53DNkqV+RQWlnNf9cW6AI3QyxjABM3AWJ6BlKfUnsRDYVBCKevDoN7VlDqDtPTJShpFosY96pgmv++Oor9A3+Clf/KjI4+8OgGAosKDmadZmlUgCR3EyS1Fmg+E82eAsYgFgYviCPkMxyo4QTJbd24Ooj7MDvCdP/6RO6u60CnHrkQpHciNmTZbUgDicuVjH92bo4R8bM4l7H4uSwL0axMI=
